# Generated by Django 4.2.13 on 2024-05-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acdj', '0002_remove_caraccessory_description_remove_carmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caraccessory',
            name='price',
            field=models.FloatField(),
        ),
    ]
