# Generated by Django 4.2.13 on 2024-06-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acdj', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='paymentData',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
