# Generated by Django 4.2.13 on 2024-06-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acdj', '0005_carbrand_paymentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='paymentData',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
