# Generated by Django 4.2.13 on 2024-06-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acdj', '0006_alter_carbrand_paymentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='caraccessory',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
